### ISSUE TITLE
Is original author is still interested in working on this plugin? 

### ISSUE THREAD

**Issue by paaloeye** [jedi4ever/sahara#58]
@jedi4ever, 
The plugin is bit outdated as of now.  
But the idea behind it is quite cool.
I would like to jump in. What do you think?

**Comment by legal90** [comment]
Hi @Paulche,
I'm not a maintainer but want to put my 2 cents.
Currently, the same functionality is available in Vagrant out-of-box, refer to `vagrant snapshot` command:
https://www.vagrantup.com/docs/cli/snapshot.html
Does it work for you?

`sahara` is an awesome plugin and most likely, Vagrant authors were inspired by it while implementing the "native" snapshot support. But currently, it looks obsolete.

**Comment by paaloeye** [comment]
@legal90 I'm quite surprised about the presence of `snapshot` functionality in Vagrant itself. That's exactly what I was looking for. Thank you!

Given the fact above there is no point to maintain `vagrant-sahara` anymore.
A short reference to `shapshot` command would have saved me some time.
